import {createCharacter} from './setup';
import {test,expect,type Page,type Locator} from '@playwright/test';
async function boot(page:Page){await page.goto('/');await createCharacter(page);await expect(page.getByTestId('tabletop')).toBeVisible();await page.getByRole('button',{name:'收起提示'}).click();}
async function drag(page:Page,source:Locator,to:{x:number;y:number}){const r=await source.boundingBox();if(!r)throw Error('missing source');await page.mouse.move(r.x+r.width/2,r.y+Math.min(30,r.height/2));await page.mouse.down();await page.mouse.move(to.x,to.y,{steps:14});await page.mouse.up();}
async function fill(page:Page,slot:string,id:string){await page.getByTestId('slot-'+slot).click();await page.getByTestId('card-'+id).click();await expect(page.getByTestId('slot-'+slot).locator('.slotted-card')).toHaveCount(1);}
async function act(page:Page,verb:string,focus:string){await page.getByRole('button',{name:verb,exact:true}).click();await fill(page,'actor','character.learner');await fill(page,'focus',focus);await page.getByRole('button',{name:'开始行事',exact:false}).click();await page.getByRole('button',{name:'等候下一进展'}).click();await expect(page.getByRole('button',{name:'收取成果',exact:false})).toBeVisible();}
async function collect(page:Page){await page.getByRole('button',{name:'收取成果',exact:false}).click();await page.locator('.verb-window').getByRole('button',{name:'关闭窗口'}).click();}
test('自由桌面：告示变成住处线索、手动收取、刷新保留未收取结果',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await boot(page);await expect(page.locator('.m-chain,.m-nav')).toHaveCount(0);await expect(page.getByTestId('money')).toHaveText('24');await page.screenshot({path:'docs/screenshots/凡尘-自由桌面.png',fullPage:true});
 await act(page,'行游','thread.CH01.0');await expect(page.getByTestId('card-character.learner')).toHaveCount(0);await expect(page.locator('.result-cards')).toContainText('今夜的住处');await expect(page.getByRole('button',{name:'保存状态'})).toContainText('已保存到本机');await page.reload();await expect(page.locator('.verb-node.result-ready')).toHaveCount(1);await page.getByRole('button',{name:'行游',exact:true}).click();await collect(page);await expect(page.getByTestId('card-thread.CH01.1')).toBeVisible();
 await act(page,'谋生','thread.CH01.1');await expect(page.getByTestId('money')).toHaveText('30');await collect(page);await act(page,'谋生','thread.CH01.2');await expect(page.getByTestId('money')).toHaveText('42');await page.screenshot({path:'docs/screenshots/凡尘-行动回响.png',fullPage:true});await collect(page);await page.getByRole('button',{name:'人物志',exact:true}).click();await expect(page.locator('.situation-block').first()).toBeVisible();expect(errors).toEqual([]);
});
test('真实拖拽与预览不扣款、可取回、取消释放卡牌',async({page})=>{
 await boot(page);await page.getByRole('button',{name:'行游',exact:true}).click();const box=await page.getByTestId('slot-actor').boundingBox();await drag(page,page.getByTestId('card-character.learner'),{x:box!.x+40,y:box!.y+45});await expect(page.getByTestId('slot-actor').locator('.slotted-card')).toHaveCount(1);await fill(page,'focus','thread.CH01.0');await expect(page.getByTestId('money')).toHaveText('24');await page.getByRole('button',{name:'取回用工告示'}).click();await expect(page.getByRole('button',{name:'开始行事',exact:false})).toBeDisabled();await fill(page,'focus','thread.CH01.0');await page.getByRole('button',{name:'开始行事',exact:false}).click();await page.getByRole('button',{name:'取消行事'}).click();await expect(page.getByTestId('card-character.learner')).toBeVisible();await expect(page.getByTestId('card-thread.CH01.0')).toBeVisible();await expect(page.getByTestId('money')).toHaveText('24');
});
test('地点卡出行、食宿窗口、存档可用',async({page})=>{
 await boot(page);await act(page,'行游','thread.CH01.0');await collect(page);await page.getByRole('button',{name:'行游',exact:true}).click();await drag(page,page.locator('.verb-window .window-handle'),{x:600,y:610});await fill(page,'actor','character.learner');await fill(page,'focus','location.inn');await page.getByRole('button',{name:'开始行事',exact:false}).click();await page.getByRole('button',{name:'等候下一进展'}).click();await collect(page);await expect(page.locator('.location-now')).toContainText('河埠客舍');await page.getByRole('button',{name:'起居',exact:true}).click();await expect(page.getByRole('dialog',{name:'食宿与起居'})).toContainText('安顿此身');await page.locator('.ledger-window').getByRole('button',{name:'关闭窗口'}).click();await page.getByRole('button',{name:'存档',exact:true}).click();await expect(page.getByRole('button',{name:'导出存档'})).toBeVisible();
});
