import {test,expect} from '@playwright/test';
import {createCharacter} from './setup';
test('独行试验、收藏准备、存取档及跨局手札',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await createCharacter(page);await page.getByRole('button',{name:'收起提示'}).click();
 await page.getByRole('button',{name:'手札',exact:true}).click();const panel=page.getByRole('dialog',{name:'研究与个人手札'});
 await panel.getByRole('button',{name:'开启研究手札'}).click();await panel.getByRole('button',{name:'采集／抄录'}).click();await panel.getByRole('button',{name:'等候研究进展'}).click();
 await panel.getByRole('button',{name:'青叶草'}).click();await panel.getByRole('button',{name:'收藏当前组合'}).click();await panel.getByLabel('收藏名称',{exact:true}).fill('我的基础药膏');await panel.getByLabel('个人备注').fill('未试过也能收藏');await panel.getByRole('button',{name:'保存收藏',exact:true}).click();await expect(panel).toContainText('本局待验证');
 await panel.getByRole('button',{name:'准备已有材料'}).click();await expect(panel.getByRole('button',{name:'青叶草'})).toHaveAttribute('aria-pressed','true');await panel.getByRole('button',{name:'执行试验',exact:true}).click();await panel.getByRole('button',{name:'等候研究进展'}).click();await expect(panel).toContainText('得到基础药膏');
 await panel.getByRole('button',{name:'知识与笔记'}).click();await expect(panel).toContainText('已发现固定方法：青叶草');await page.screenshot({path:'docs/screenshots/研究-知识与笔记.png',fullPage:true});
 await panel.getByRole('button',{name:'个人收藏',exact:true}).click();await expect(panel).toContainText('本局 1 次观察');await panel.getByRole('button',{name:'编辑',exact:true}).click();await panel.getByLabel('青叶草数量').fill('2');await panel.getByRole('button',{name:'保存收藏',exact:true}).click();await expect(panel).toContainText('组合版本 2');await expect(panel).not.toContainText('本局 1 次观察');
 await expect(page.getByLabel('保存状态')).toContainText('已保存');await page.reload();await page.getByRole('button',{name:'手札',exact:true}).click();await panel.getByRole('button',{name:'个人收藏',exact:true}).click();await expect(panel).toContainText('我的基础药膏');await expect(panel).toContainText('组合版本 2');await page.screenshot({path:'docs/screenshots/研究-个人收藏.png',fullPage:true});
 await panel.getByRole('button',{name:'关闭窗口'}).click();await page.getByRole('button',{name:'存档',exact:true}).click();await page.getByRole('button',{name:'开启新旅程'}).click();await page.getByRole('button',{name:'确认重新开始'}).click();await createCharacter(page);await page.getByRole('button',{name:'手札',exact:true}).click();await panel.getByRole('button',{name:'个人收藏',exact:true}).click();await expect(panel).toContainText('我的基础药膏');await expect(panel).toContainText('缺少 2');await panel.getByRole('button',{name:'知识与笔记'}).click();await expect(panel).toContainText('已发现固定方法：青叶草');expect(errors).toEqual([]);
});
test('窄屏研究准备不产生消耗',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await createCharacter(page);await page.getByRole('button',{name:'收起提示'}).click();await page.getByRole('button',{name:'手札',exact:true}).click();const panel=page.getByRole('dialog',{name:'研究与个人手札'});await panel.getByRole('button',{name:'开启研究手札'}).click();await panel.getByRole('button',{name:'青叶草'}).click();await expect(page.getByTestId('money')).toHaveText('24');await panel.getByRole('button',{name:'执行试验',exact:true}).click();await expect(panel.getByRole('button',{name:'等候研究进展'})).toHaveCount(0);await page.screenshot({path:'docs/screenshots/研究-窄屏准备.png',fullPage:true});
});
