import {test,expect,type Page} from '@playwright/test';
import {createCharacter} from './setup';
async function fill(page:Page,slot:string,id:string){await page.getByTestId('slot-'+slot).click();await page.getByTestId('card-'+id).click();}
async function collect(page:Page){await page.getByRole('button',{name:'收取成果',exact:false}).click();await page.locator('.verb-window').getByRole('button',{name:'关闭窗口'}).click();}
async function boot(page:Page){await page.goto('/');await createCharacter(page);await page.getByRole('button',{name:'收起提示'}).click();}
async function stage(page:Page,verb:string,focus:string){await page.getByTestId('verb-'+verb).click();await fill(page,'actor','character.learner');await fill(page,'focus',focus);await page.getByRole('button',{name:'开始行事',exact:false}).click();await page.getByRole('button',{name:'等候下一进展'}).click();await collect(page);}
test('租房后在集市直接休息，关闭运行窗口仍能找到自身和铺位',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await boot(page);await stage(page,'travel','thread.CH01.0');await stage(page,'talk','thread.CH01.1');await expect(page.locator('.location-now')).toContainText('青溪集');await page.getByTestId('verb-cultivate').click();await fill(page,'actor','character.learner');await fill(page,'focus','shelter.bed');await expect(page.getByRole('heading',{name:'返回客舍歇息'})).toBeVisible();await expect(page.locator('.story-text')).toContainText('20 分钟');await expect(page.getByRole('button',{name:'开始行事',exact:false})).toBeEnabled();await page.getByRole('button',{name:'开始行事',exact:false}).click();await page.locator('.verb-window').getByRole('button',{name:'关闭窗口'}).click();const tray=page.getByTestId('card-locations');await expect(tray).toContainText('陆青禾');await expect(tray).toContainText('客舍铺位');await expect(page.getByTestId('card-character.learner')).toHaveCount(0);await page.screenshot({path:'docs/screenshots/凡尘-卡牌去向.png',fullPage:true});await tray.getByRole('button').click();await page.getByRole('button',{name:'等候下一进展'}).click();await page.locator('.verb-window').getByRole('button',{name:'关闭窗口'}).click();await expect(tray).toContainText('待收取');await tray.getByRole('button').click();await collect(page);await expect(page.locator('.location-now')).toContainText('河埠客舍');await expect(page.getByTestId('money')).toHaveText('20');await expect(page.getByTestId('card-character.learner')).toBeVisible();await expect(tray).toHaveCount(0);expect(errors).toEqual([]);
});
test('未开始的卡牌在关闭、Esc、切换动词后回到桌面原位',async({page})=>{
 await boot(page);const card=page.getByTestId('card-character.learner'),before=await card.boundingBox();await page.getByTestId('verb-travel').click();await fill(page,'actor','character.learner');await fill(page,'focus','thread.CH01.0');await page.locator('.verb-window').getByRole('button',{name:'关闭窗口'}).click();await expect(card).toBeVisible();expect((await card.boundingBox())!.x).toBeCloseTo(before!.x,0);await expect(page.getByTestId('card-thread.CH01.0')).toBeVisible();await page.getByTestId('verb-travel').click();await fill(page,'actor','character.learner');await page.keyboard.press('Escape');await expect(card).toBeVisible();await stage(page,'travel','thread.CH01.0');await page.getByTestId('verb-talk').click();await fill(page,'actor','character.learner');await fill(page,'focus','thread.CH01.1');await page.getByTestId('verb-work').click();await expect(card).toBeVisible();await expect(page.getByTestId('card-thread.CH01.1')).toBeVisible();await expect(page.getByTestId('slot-actor').locator('.slotted-card')).toHaveCount(0);await page.getByTestId('verb-talk').click();await expect(page.getByTestId('slot-actor').locator('.slotted-card')).toHaveCount(0);await expect(page.getByTestId('money')).toHaveText('24');
});
