import {knownVerbs,verbNames} from '../domain/mortal-discovery';
import {useState} from 'react';
import {PLAYER,type World,type Command} from '../domain/model';
import {session} from '../application/game-session';
import {places} from '../content/mortal';
import {Meter} from './Panels';
export function MortalPanels({panel,w,notify}:{panel:string;w:World;notify:(s:string)=>void}){
 const [query,setQuery]=useState(''),[page,setPage]=useState(0);
 const m=w.mortal,p=w.entities[PLAYER],people=Object.values(m.people).filter(x=>(x.name+x.anchors.join('')+x.memories.join('')).includes(query));
 const send=(c:Command)=>{const r=session.command(c);if(!r.ok)notify(r.message);};
 if(panel==='organization')return <><h2>安顿此身</h2><p>存粮 {m.foodDays} 日 · 钱文 {w.money} 文</p><p>{m.paidUntil>w.tick?'铺位已付至第 '+(Math.floor(m.paidUntil/1440)+1)+' 日':'尚无有效铺位'}</p><p className="story-text">将自身与客舍投入「交游」，支付 4 文续住两日；投入「谋生」，可以用劳动换食宿。将自身、青溪集和钱文投入「交游」，购买两日口粮。把自身与已租的铺位投入「修养」，即可返回客舍歇息，返程时间一并计算。</p><Meter label="健康" value={p.health}/><Meter label="疲劳" value={p.fatigue}/><p className="muted">饮食先用存粮，用尽后每天支出 2 文。已付房租不重复扣取。</p><h3>近期收支</h3>{m.ledger.slice(-12).reverse().map(e=><p key={e.id} className="muted">{e.reason} · {e.amount} 文 · {e.from===PLAYER?'支出':e.to===PLAYER?'收入':'委托结算'}</p>)}</>;
 if(panel==='character')return <><h2>{p.name}</h2><p>{Math.floor(p.ageMinutes/525600)} 岁 · {p.description}</p><Meter label="健康" value={p.health}/><Meter label="疲劳" value={p.fatigue}/><h3>已练之艺</h3>{Object.entries({medicine:'药理',craft:'工艺',scholar:'学问',music:'音律'}).map(([id,name])=><p key={id}>{name} · {m.skills[id]??0}</p>)}<h3>亲手完成</h3>{w.works.length?w.works.map(x=><p key={x.id}>《{x.title}》</p>):<p className="muted">尚无作品。线索会在你走访各处时来到桌面。</p>}<h3>相识与旧友</h3><input aria-label="查找相识" placeholder="姓名或共同经历" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/>{people.slice(page*10,page*10+10).map(x=><article className="situation-block" key={x.id}><b>{x.name} · {x.retentionClass==='important'?'记挂的人':'相识'}</b><span>{x.knownStatus}</span><small>{x.anchors.join('；')}</small><small>{x.memories.at(-1)}</small><div className="button-row"><button className="text-button" onClick={()=>send({type:'MortalContact',personId:x.id,operation:'bookmark'})}>{x.retentionClass==='important'?'取消关注':'记挂此人'}</button><button className="text-button" disabled={!x.contact||x.worldStatus==='dead'} onClick={()=>send({type:'MortalContact',personId:x.id,operation:'letter'})}>寄信 · 1 文</button></div></article>)}{!people.length&&<p className="muted">尚未相识。行动中遇到的人会记在这里。</p>}{people.length>10&&<div className="button-row"><button disabled={!page} onClick={()=>setPage(page-1)}>上一页</button><span>{page+1} / {Math.ceil(people.length/10)}</span><button disabled={(page+1)*10>=people.length} onClick={()=>setPage(page+1)}>下一页</button></div>}<h3>在途消息</h3>{Object.values(m.messages).slice(-8).map(x=><p key={x.id}>{m.people[x.personId]?.name} · {x.state==='travelling'?'信件在途':x.state==='delivered'?'已收到回信':'退回'}</p>)}</>;
 return <><p className="intro-quote">“路不是预先画好的，是一步步走出来的。”</p><div className="help-steps"><p><b>案上</b>拖动卡牌与行动方块，自由摆放。拖空白移动桌面，滚轮缩放。右下角可以整理与归位。</p><p><b>尝试</b>打开一个已发现的行动，投入自身与手头的卡牌。可拖入，也可点击槽位后点击发亮的卡牌；双击也能投入。开始前的摆放不会扣钱。关闭或切换行动，未开始的卡牌会退回原位。</p><p><b>回响</b>行动计时结束后，打开发亮的方块，收取卡牌。新的人、物与去处来自这段经历；有时你也会发现新的做事方式。桌面的「卡牌去向」会列出进行中和待收取的卡牌，点击即可打开对应行动。暂时没有回应的组合，可以留待以后。</p></div><h3>你已发现的行事</h3>{knownVerbs(w).map(v=><p key={v}>{verbNames[v]} · {({travel:'去一个已知的地方，或带着线索找一找。',talk:'向相识打听，或商量手头的事情。',work:'工具、工作约定与完成的作品，都可能换来生计。',cultivate:'在住处歇息，也可以尝试已经获得的方法。',study:'图册、疑点与方法，值得花时间理解。',create:'已有的准备，可以尝试做成一件东西。'}[v])}</p>)}<p className="muted">当前所在：{places.find(x=>x.id===p.location)?.name}。空格暂停时间；离开页面后保持暂停。</p></>;
}
