import {useEffect,useRef,useState} from 'react';
import {ArrowRight,BookOpen,Check,Clock3,Coins,Leaf,MapPin,Pause,Play,Save,SkipForward,Users,X} from 'lucide-react';
import {session,type Snapshot} from '../application/game-session';
import {PLAYER,type Command} from '../domain/model';
import {backgrounds,chains,methods,places,roles,shortSeeds} from '../content/mortal';
import {chainDone,done,previewMortal} from '../domain/mortal';
import {Illustration} from './Glyph';
import './mortal.css';
const date=(tick:number)=>'第 '+(Math.floor(tick/1440)+1)+' 日 · '+String(Math.floor(tick%1440/60)).padStart(2,'0')+':'+String(tick%60).padStart(2,'0');
const duration=(n:number)=>n>=60?Math.floor(n/60)+' 小时'+(n%60?' '+n%60+' 分':''):n+' 分钟';
const art=(id:string)=>({'location.market':'market','location.inn':'pavilion','location.pharmacy':'herb','location.garden':'garden','location.pavilion':'pavilion','location.teahouse':'pavilion','location.study':'study','location.workshop':'furnace','location.mountain':'mountain','location.temple':'mountain'} as Record<string,string>)[id]??'scroll';
export function MortalApp({state}:{state:Snapshot}){
 const w=state.world,m=w.mortal,p=w.entities[PLAYER];
 const [tab,setTab]=useState<'desk'|'map'|'people'|'journal'|'save'>('desk'),[name,setName]=useState('陆青禾'),[origin,setOrigin]=useState<typeof m.origin>('traveller'),[talent,setTalent]=useState<typeof m.talent>('steady'),[acquaintance,setAcquaintance]=useState(false);
 const [selected,setSelected]=useState<string>('CH01'),[option,setOption]=useState(''),[search,setSearch]=useState(''),[personPage,setPersonPage]=useState(0),[notice,setNotice]=useState(''),[confirmReset,setConfirmReset]=useState(false),[font,setFont]=useState(state.tabletop.accessibility?.fontSize??100),[reduced,setReduced]=useState(state.tabletop.accessibility?.reducedMotion??true);
 const [actorLoaded,setActorLoaded]=useState(false),input=useRef<HTMLInputElement>(null);
 const readonly=!state.ready||state.pauses.includes('read_only'),task=m.task;
 const chain=chains.find(c=>c.id===selected),stage=chain?.stages[m.stages[selected]??0],preview=previewMortal(w,selected,option);
 const here=places.find(l=>l.id===p.location)!;
 const contacts=Object.values(m.people).filter(x=>(x.name+x.anchors.join('')+x.memories.join('')).includes(search));
 const uiDone=(id:string)=>id==='CH10'?m.flags.some(f=>f.startsWith('applied.')):chainDone(w,id);
 useEffect(()=>{if(state.tabletop.accessibility){setFont(state.tabletop.accessibility.fontSize);setReduced(state.tabletop.accessibility.reducedMotion);}},[state.tabletop.accessibility]);
 const select=(id:string,choice='')=>{setSelected(id);setOption(choice);setActorLoaded(false);};
 const send=(c:Command)=>{const r=session.command(c);if(!r.ok)setNotice(r.message);else setNotice('');return r;};
 useEffect(()=>{const timer=setInterval(()=>session.advance(5*session.getSnapshot().speed),500);const vis=()=>{if(document.hidden)session.hidden();};document.addEventListener('visibilitychange',vis);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',vis);};},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.code==='Space'&&!['INPUT','SELECT','BUTTON','TEXTAREA'].includes((e.target as HTMLElement).tagName)){e.preventDefault();session.togglePause();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const exportSave=()=>{const url=URL.createObjectURL(new Blob([session.export()],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='山河问道-凡尘篇.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const button=(text:string,actionId:string,choice='',primary=false)=><button className={primary?'m-primary':''} disabled={readonly||!!task} onClick={()=>{select(actionId,choice);setTab('desk');}}>{text}<ArrowRight size={14}/></button>;
 return <main className={'mortal-app '+(reduced?'reduce-motion':'')} style={{fontSize:(font/100*15)+'px'}}>
 <header className="m-header"><div className="m-brand"><span>山<br/>河</span><div><h1>山河问道</h1><small>凡尘篇 · 从此处安身</small></div></div><div className="m-purse"><Coins size={17}/><b data-testid="money">{w.money}</b> 文<span className="m-separator"/><MapPin size={15}/>{here.name}</div><div className="m-clock"><span>{date(w.tick)}</span><button aria-label={state.pauses.length?'继续时间':'暂停时间'} onClick={()=>session.togglePause()}>{state.pauses.length?<Play size={16}/>:<Pause size={16}/>}</button>{[1,3,6].map(v=><button key={v} aria-label={v+'倍速度'} className={state.speed===v?'active':''} onClick={()=>session.setSpeed(v)}>{v}×</button>)}</div></header>
 {!m.created?<section className="m-creation"><div className="m-opening-art"><Illustration kind="mountain"/><span>渡口 · 青溪</span></div><div className="m-creation-body"><small className="m-eyebrow">你的人生，自此展开</small><h2>包袱还在。<br/>下一顿饭，尚无着落。</h2><p>渡船把你放在青溪岸边。集口贴着几张用工告示，远处有人在试一段未完的曲子。</p><label>你的姓名<input value={name} maxLength={16} onChange={e=>setName(e.target.value)}/></label><label>从前的生活<select value={origin} onChange={e=>{setOrigin(e.target.value as typeof origin);setAcquaintance(false);}}>{backgrounds.map(b=><option key={b.id} value={b.id}>{b.name} · {b.tool}</option>)}</select></label><p className="m-note">{backgrounds.find(b=>b.id===origin)?.skill?'对应凡人技艺已有一点基础。其他路线仍可学习。':'没有既定职业，可从公开短工尝试四条生计。'} 24 文、两日干粮、一件普通工具。没有药园或完整修法。</p><label>显著天赋<select value={talent} onChange={e=>setTalent(e.target.value as typeof talent)}><option value="steady">耐心 · 试行练习缩短 30 分钟</option><option value="observant">善察 · 辨药学习缩短 30 分钟</option><option value="focused">专注 · 理解方法缩短 30 分钟</option></select></label>{origin!=='traveller'&&<label className="m-check"><input type="checkbox" checked={acquaintance} onChange={e=>setAcquaintance(e.target.checked)}/>记得一位旧同行：浅交，在外地，可寄信；没有宗门资源。</label>}<button className="m-primary" disabled={readonly||!name.trim()} onClick={()=>send({type:'CreateMortal',name,origin,talent,acquaintance})}>踏上青溪岸 <ArrowRight size={16}/></button></div></section>:<>
 <nav className="m-nav">{([['desk','案上行事',Leaf],['map','远近山河',MapPin],['people','相识与旧友',Users],['journal','此生记事',BookOpen],['save','存档与设置',Save]] as const).map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={16}/>{label}</button>)}</nav>
 <div className="m-layout"><aside className="m-sidebar"><button className={'m-person '+(actorLoaded?'loaded':'')} draggable={!task} onDragStart={e=>e.dataTransfer.setData('text/plain',PLAYER)} onClick={()=>setActorLoaded(true)} aria-label="投入自身"><Illustration kind="player"/><b>{p.name}</b><small>{task?'正在行事':'自身 · 可点击或拖入行事'}</small></button><div className="m-vitals"><label>健康 <b>{p.health}</b></label><meter value={p.health} max={100}/><label>疲劳 <b>{p.fatigue}</b></label><meter value={p.fatigue} max={100}/></div><div className="m-life"><span>储粮 <b>{m.foodDays} 日</b></span><span>床位 <b>{m.paidUntil>w.tick?'付至第 '+(Math.floor(m.paidUntil/1440)+1)+' 日':'待安顿'}</b></span><small>饮食 2 文/日，优先用储粮。床位 2 文/日，手动续付。</small></div><div className="m-tools"><small>随身物件</small>{Object.values(m.assets).filter(a=>a.kind==='item'&&a.ownerId===PLAYER&&a.status==='available').map(a=><p key={a.id}>{a.name}</p>)}<small>工具不锁定职业</small></div><h3>此刻所求</h3>{([['life','安顿生活'],['work','做成一件事'],['path','寻找可靠门路']] as const).map(([id,label])=><button key={id} className={'m-goal '+(m.focus===id?'active':'')} onClick={()=>send({type:'MortalFocus',focus:id})}>{(id==='life'?done(w,'income')&&done(w,'shelter'):id==='work'?w.works.length>0:chainDone(w,'CH09'))?<Check size={14}/>:<span>◇</span>}{label}</button>)}<p className="m-note">{m.focus==='life'?'先看集口告示；也可以直接到客舍商量食宿。':m.focus==='work'?'从药铺、作坊、书院或听雨亭选一门技艺；可以随时换一条路。':'到书院询问公开课；或购入基础注本自行核对。三种渠道都不要求战斗。'}</p></aside>
 <section className="m-content">
 {tab==='desk'&&<><div className="m-section-title"><div><small className="m-eyebrow">{here.description}</small><h2>{m.completed?'此生已有第一缕光':'先在这人间，做成一件事。'}</h2></div><span>生活与求道，可以并行</span></div>
 {m.completed&&<div className="m-complete">凡尘篇初修已达成。食宿、作品、相识和修持都已留下；可以继续生活，不必立刻入宗。</div>}
 <div className="m-verbs" aria-label="六种行事">{[['研习','medicine'],['交游','people'],['创作','CH04'],['谋生','work'],['修养','rest'],['行游','map']].map(([name,target])=><button key={name} onClick={()=>{if(target==='people'||target==='map')setTab(target);else select(target);}}><span>◇</span>{name}</button>)}</div>
 <div className="m-chain-row">{chains.filter(c=>c.requires.every(id=>chainDone(w,id))).map(c=><button className={'m-chain '+(selected===c.id?'selected':'')+(uiDone(c.id)?' complete':'')} key={c.id} onClick={()=>select(c.id)}><small>{c.id} · {c.skill?({medicine:'医药',craft:'手艺',music:'音律',scholar:'学问'} as Record<string,string>)[c.skill]:'人生际遇'}</small><b>{c.name}</b><span>{uiDone(c.id)?'✓ 已完成':c.id==='CH10'&&chainDone(w,c.id)?'准备完成 · 待修持应用':(m.stages[c.id]??0)+' / '+c.stages.length+' 段经历'}</span></button>)}</div>
 <section className="m-bench" aria-label="行事台" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(e.dataTransfer.getData('text/plain')===PLAYER)setActorLoaded(true);}}>
 {task?<><small className="m-eyebrow">人和物正在这段经历里</small><h2>{chains.find(c=>c.id===task.actionId)?.name??previewMortal({...w,mortal:{...m,task:null}},task.actionId,task.choice).name}</h2><p>还需 {duration(Math.max(0,task.dueTick-w.tick))}。取消会保留已经花费的时间与开工材料，未付报酬退回。</p><progress max={task.dueTick-task.startedTick} value={w.tick-task.startedTick}/><div className="m-button-row"><button className="m-primary" onClick={()=>session.waitForAction()}><SkipForward size={16}/>推进到下一项结果</button><button onClick={()=>send({type:'CancelMortal'})}>取消并结清</button></div></>:<><div className="m-bench-heading"><span className="m-bench-symbol">◇</span><div><small>{chain?.name??'生活安排'}</small><h2>{stage?.name??preview.name}</h2></div><button className={'m-slot '+(actorLoaded?'filled':'')} onClick={()=>setActorLoaded(!actorLoaded)} aria-label="自身槽位">{actorLoaded?p.name:'＋ 投入自身'}</button></div><p className="m-story">{stage?.text??(chainDone(w,selected)?selected==='CH10'&&!m.applied?'准备已经完成。到下方「可靠方法」选择方法，再依次理解、试行、纠错、重复验证和实际应用。':'这段经历已经留下，可以继续本业，或看看其他方向。':preview.detail)}</p>{stage&&<div className="m-choices">{stage.choices.map(c=><button key={c.id} className={option===c.id?'chosen':''} onClick={()=>setOption(c.id)}><b>{c.text}</b><span>{c.detail}</span><small><Clock3 size={12}/>{duration(c.minutes)}{c.cost?' · 支出 '+c.cost+' 文':''}{c.reward?' · 完成得 '+c.reward+' 文':''}</small></button>)}</div>}
 <div className="m-preview"><span><Clock3 size={14}/>{duration(preview.minutes)}</span><span>开工消耗 {preview.cost} 文</span><span>完成报酬 {preview.reward} 文</span><span>占用自身{preview.role?'与现场合作者':''}</span></div><p className="m-note">{preview.detail} 取消不返还开工材料；阶段可重试。长行动照常结算食物、行程和来信。</p>{preview.errors.length>0&&<div className="m-errors">{preview.errors.map((e,i)=><p key={i}>{e}</p>)}{preview.location&&p.location!==preview.location&&button('先前往'+places.find(l=>l.id===preview.location)?.name,'travel.'+preview.location,'',true)}</div>}<button className="m-primary" disabled={readonly||!actorLoaded||preview.errors.length>0} onClick={()=>{if(send({type:'MortalAction',actionId:selected,choice:option}).ok)setActorLoaded(false);}}>开始这段行事 <ArrowRight size={15}/></button>{!actorLoaded&&<small className="m-inline-hint">点击左侧人物，或点「投入自身」。</small>}</>}
 </section>
 <section className="m-quick"><h3>谋生与起居</h3><div className="m-button-row">{button('公共短工 · 12 文','work')}{button('低强度工作 · 8 文','work','light')}{button('包食宿帮工','relief')}{button('歇息调养','rest')}{button('续住两日 · 4 文','rent')}{button('储备两日食物 · 4 文','food')}</div>{chains.filter(c=>c.skill&&chainDone(w,c.id)).map(c=><div className="m-job" key={c.id}>{button('接续'+c.name+'的专业委托','job.'+c.id)}</div>)}{done(w,'income')&&<div className="m-plan"><span>安排三次低强度短工：疲劳达 60、缺食宿或遇消息暂停。</span><button disabled={readonly} onClick={()=>send({type:'MortalPlan',days:m.plan?0:3,stopFatigue:60})}>{m.plan?'停止后续安排':'安排后续工作'}</button></div>}</section>
 {chainDone(w,'CH09')&&<section className="m-methods"><h3>可靠方法 · 分开理解、实践与应用</h3><div className="m-button-row">{methods.map(d=>button(d.name+(m.method===d.id?' · 当前':''),'method',d.id))}</div>{m.method&&<><p>{methods.find(d=>d.id===m.method)?.requirement}</p><div className="m-milestones"><span>理解 {m.understanding}/2</span><span>有效实践 {Math.min(3,m.practice)}/3</span><span>纠错 {m.corrected?'✓':'待完成'}</span><span>应用 {m.applied?'✓':'待完成'}</span></div><div className="m-button-row">{button('理解步骤','understand')}{button('试行 / 复验','practice')}{button('比对注本纠错','correct')}{button('实际应用','apply')}{button('公开辨药课','medicine')}</div></>}</section>}
 {Object.values(m.shortEvents).some(e=>e.state==='open')&&<section className="m-inbox"><h3>身边小事 · 阅读不耗时</h3>{Object.values(m.shortEvents).filter(e=>e.state==='open').map(e=>{const d=shortSeeds.find(s=>s.id===e.id)!;return <article key={e.id}><b>{d.name}</b><div className="m-button-row"><button onClick={()=>send({type:'MortalEvent',eventId:e.id,choice:'act'})}>{d.act}</button><button onClick={()=>send({type:'MortalEvent',eventId:e.id,choice:'decline'})}>{d.decline}</button></div></article>;})}</section>}
 </>}
 {tab==='map'&&<><div className="m-section-title"><div><small className="m-eyebrow">城内近行，山路先做准备</small><h2>青溪与远山</h2></div></div><div className="m-map-grid">{places.map(l=><article className={'m-place '+(p.location===l.id?'here':'')} key={l.id}><div><Illustration kind={art(l.id)}/></div><small>{p.location===l.id?'此刻所在':'可达之处'}</small><h3>{l.name}</h3><p>{l.description}</p>{button('行游 · '+(['location.mountain','location.temple'].includes(l.id)?'3 小时':'20 分钟'),'travel.'+l.id)}</article>)}</div></>}
 {tab==='people'&&<><div className="m-section-title"><div><small className="m-eyebrow">相遇有来历，离开有去处</small><h2>旧识仍是那个人</h2></div></div><input aria-label="搜索旧友" placeholder="按姓名、职业或经历搜索" value={search} onChange={e=>{setSearch(e.target.value);setPersonPage(0);}}/><p className="m-note">现场 {Object.values(m.people).filter(x=>x.simulationTier==='L2').length} · 联系人 {Object.values(m.people).filter(x=>x.simulationTier==='L1').length} · 旧识档案 {Object.values(m.people).filter(x=>x.simulationTier==='A').length}。关注不会让远方的人立即出现。</p>{contacts.slice(personPage*24,(personPage+1)*24).map(person=><article className="m-contact" key={person.id}><div className="m-contact-title"><h3>{person.name}</h3><small>{roles.find(r=>r.id===person.role)?.name} · {person.retentionClass==='important'?'已关注':'普通相识'}</small></div><p>{person.knownStatus}</p>{m.relationships[person.id]&&<p className="m-note">{m.relationships[person.id].kind==='guide'?'有限指导':m.relationships[person.id].kind==='colleague'?'同业合作':'普通相识'} · 信任 {m.relationships[person.id].trust} · {m.relationships[person.id].facts.at(-1)}</p>}<p className="m-note">{person.anchors.join('；')}。</p><p className="m-note">{person.contact||'未约定后续联系'}{person.departAt?' · 计划第 '+(Math.floor(person.departAt/1440)+1)+' 日离开':''}</p><details><summary>共同经历与未完事项</summary>{person.memories.map((text,i)=><p key={i}>{text}</p>)}{person.pins.map(pin=><p key={pin.ownerId}>◇ {pin.pinReason}</p>)}</details><div className="m-button-row">{(['bookmark','letter','meet'] as const).map((operation,i)=><button key={operation} onClick={()=>send({type:'MortalContact',personId:person.id,operation})}>{[person.retentionClass==='important'?'取消关注':'关注此人','寄信 · 1 文 / 两日','在此地重逢'][i]}</button>)}</div></article>)}{contacts.length>24&&<div className="m-button-row"><button disabled={!personPage} onClick={()=>setPersonPage(n=>n-1)}>上一页</button><span>{personPage+1} / {Math.ceil(contacts.length/24)}</span><button disabled={(personPage+1)*24>=contacts.length} onClick={()=>setPersonPage(n=>n+1)}>下一页</button></div>}{!Object.keys(m.people).length&&<p className="m-empty">初来此地，尚无相识。一次工作、一段合奏，都会让某个人留下名字。</p>}</>}
 {tab==='journal'&&<><h2>此生留下的事</h2><details><summary>钱款账本 · 工作预留与实际支出</summary>{m.ledger.slice(-60).reverse().map(e=><p className="m-note" key={e.id}>{date(e.tick)} · {e.reason} · {e.amount} 文 · {e.from===PLAYER?'自己':'委托方'} → {e.to===PLAYER?'自己':e.to==='regional.work'?'委托方':'服务或托管'}</p>)}</details><div className="m-works">{w.works.map(work=><article key={work.id}><BookOpen size={24}/><h3>《{work.title}》</h3><small>{date(work.tick)} · {p.name}</small></article>)}</div>{w.log.slice().reverse().map(l=><article className={'m-log '+l.kind} key={l.id}><small>{date(l.tick)}</small><p>{l.text}</p></article>)}</>}
 {tab==='save'&&<><h2>把这段人生留下</h2><p role="status">{state.saveStatus}</p><div className="m-button-row"><button onClick={()=>void session.save()}>保存此刻</button><button onClick={exportSave}>导出存档</button><button onClick={()=>input.current?.click()}>导入存档</button><button onClick={()=>void session.recover().then(()=>setNotice('已恢复备份')).catch(e=>setNotice(e.message))}>恢复备份</button></div><input ref={input} type="file" hidden accept=".json" onChange={e=>{const f=e.target.files?.[0];if(f)void f.text().then(t=>session.import(t)).catch(e=>setNotice(e.message));e.target.value='';}}/><p>存档保存在本机。旧版原型档保持原有物品、关系与权限，并在迁移时保留原快照。后台和离线时间不补算。</p><label>字体大小<select value={font} onChange={e=>{const size=Number(e.target.value) as 100|115|130;setFont(size);session.updateTabletop({...state.tabletop,accessibility:{fontSize:size,reducedMotion:reduced}});}}><option value={100}>标准</option><option value={115}>较大</option><option value={130}>大字</option></select></label><label className="m-check"><input type="checkbox" checked={reduced} onChange={e=>{setReduced(e.target.checked);session.updateTabletop({...state.tabletop,accessibility:{fontSize:font,reducedMotion:e.target.checked}});}}/>减弱动画</label><p className="m-note">当前版本无自动播放音频。所有操作可点击或使用键盘，拖拽不是必需。</p><div className="m-reset">{confirmReset?<><p>新旅程会替换当前进度。可先导出当前存档。</p><button onClick={()=>void session.reset().then(()=>{setConfirmReset(false);setTab('desk');select('CH01');}).catch(e=>setNotice(e.message))}>确认开启新旅程</button><button onClick={()=>setConfirmReset(false)}>保留此生</button></>:<button onClick={()=>setConfirmReset(true)}>开启新旅程</button>}</div></>}
 </section></div></>}
 <footer className="m-footer"><span>凡人技艺自有成果 · 修行需另求方法</span><button aria-label="保存状态" onClick={()=>setTab('save')}><Save size={13}/>{state.saveStatus}</button></footer>
 {(notice||state.notice)&&<div className="m-toast" role="status">{notice||state.notice}<button aria-label="关闭提示" onClick={()=>{setNotice('');session.clearNotice();}}><X size={15}/></button></div>}
 </main>;
}
