import {ResearchPanel} from './ResearchPanel';
import { useRef,useState } from 'react';
import { Download,Upload,Save,RotateCcw,BookOpen } from 'lucide-react';
import { PLAYER,type World,type Command } from '../domain/model';
import { content } from '../content';
import { displayDao } from '../domain/dao';
import { available,busy } from '../domain/world';
import { peopleSituations } from '../domain/people';
import { session } from '../application/game-session';
import { CardArt } from './Art';
import {MortalPanels} from './MortalPanels';
export type PanelId='research'|'character'|'organization'|'save'|'journal'|'help';
export const panelNames={research:'研究与个人手札',character:'此身与修行',organization:'青竹药园',save:'收好此刻',journal:'浮生日录',help:'桌面上的修行'};
export const timeLabel=(n:number)=>n<120?n+' 分钟':Number((n/120).toFixed(1))+' 时辰';
export const dateText=(tick:number)=>'春 '+(Math.floor(tick/1440)+1)+'日 · '+String((Math.floor(tick%1440/60)+6)%24).padStart(2,'0')+':'+String(tick%60).padStart(2,'0');
export function Meter({label,value,max=100}:{label:string;value:number;max?:number}){return <div className="meter"><span>{label}<b>{value}<small> / {max}</small></b></span><div><i style={{width:Math.min(100,value/max*100)+'%'}}/></div></div>;}
export function PanelContents({panel,w,notify,onClose}:{panel:PanelId;w:World;notify:(t:string)=>void;onClose:()=>void}){
 const [proxy,setProxy]=useState(true),[budget,setBudget]=useState(6),[confirmReset,setConfirmReset]=useState(false);const input=useRef<HTMLInputElement>(null);const p=w.entities[PLAYER];
 const send=(command:Command)=>{const r=session.command(command);if(!r.ok)notify(r.message);};
 const exportSave=()=>{const url=URL.createObjectURL(new Blob([session.export()],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='山河问道-'+dateText(w.tick).replaceAll(':','-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 if(panel==='research')return <ResearchPanel w={w} notify={notify}/>;
 if(w.mortal.mode==='chapter'&&['character','organization','help'].includes(panel))return <MortalPanels panel={panel} w={w} notify={notify}/>;
 if(panel==='character')return <><div className="person-summary"><CardArt kind="player"/><div><h2>陆青禾</h2><p>{Math.floor(p.ageMinutes/525600)} 岁 · 道行 {displayDao(p)} · 延年余裕 {p.longevityDays} 日</p><p className="muted">{p.description}</p></div></div><Meter label="健康" value={p.health}/><Meter label="疲劳" value={p.fatigue}/><h3 className="section-label">已学之艺</h3>{content.skills.map(s=><Meter key={s.id} label={s.name} value={p.skills[s.id]??0} max={s.id==='skill.music'?20:30}/>)}<h3 className="section-label">职业与进境</h3>{content.professions.map(pr=><div className="profession-row" key={pr.id}><div><b>{pr.name}</b><small>{pr.description}</small></div><button disabled={!!p.professions[pr.id]} className="brass-button" onClick={()=>send({type:'AdvanceProfession',professionId:pr.id,targetLevel:1})}>{p.professions[pr.id]?'已晋一级':'申请晋升'}</button></div>)}<p className="muted">道行只影响特殊效果抵抗与趋吉避凶。各门本领与寿数，仍需各自求索。</p><h3 className="section-label">故人处境</h3>{peopleSituations(w).map(s=><div className="situation-block" key={s.id}><b>{s.name}</b><span>{s.status}</span><small>{s.detail}</small></div>)}<h3 className="section-label">作品</h3>{w.works.length?w.works.map(x=><p className="work-entry" key={x.id}>《{x.title}》</p>):<p className="muted">尚无完成的作品。</p>}</>;
 if(panel==='organization')return <><p>一方药圃，一座丹炉，一个愿意学艺的人。</p>{!w.organization.authorized?<div className="empty-message">先把自己与「青竹药园」投入行游，再回应桌面上的托付来信。获得职事后，可以安排小满的工作。</div>:<><div className="stat-pair"><span>药园资金 <b>{w.organization.money}</b></span><span>已完成 <b>{w.organization.cycles} 轮</b></span></div><h3 className="section-label">林小满 · {busy(w,'character.worker')?'正在炼药':'空闲'}</h3><Meter label="疲劳" value={w.entities['character.worker'].fatigue}/><p className="muted">每个游戏日恢复 40 疲劳。每轮炼药需要 2 份灵草与 2 灵钱工钱。</p>{['item.herbs','item.medicine'].map(id=><div className="detail-row" key={id}><span>{content.items.find(x=>x.id===id)?.name}</span><b>{Object.values(w.entities).filter(e=>e.ownerId==='org'&&e.definitionId===id).reduce((s,e)=>s+available(w,e.id),0)} 可用</b></div>)}<div className="button-row"><button className="subtle-button" onClick={()=>send({type:'TransferItem',direction:'to_org',quantity:2})}>拨入 2 份灵草</button><button className="subtle-button" onClick={()=>send({type:'TransferItem',direction:'from_org',quantity:2})}>取回 2 份灵草</button></div><h3 className="section-label">有限的委托</h3><label className="field-label">授权预算<input type="number" value={budget} min={0} max={w.organization.money} onChange={e=>setBudget(Number(e.target.value))}/></label><label className="check-label"><input type="checkbox" checked={proxy} onChange={e=>setProxy(e.target.checked)}/> 安排代理，使自己闭关时仍可派工</label><label className="field-label">生产制度<select value={w.organization.policy} onChange={e=>send({type:'SetPolicy',policy:e.target.value as 'careful'|'productive'})}><option value="careful">劳逸相济 · 疲劳 60 停工</option><option value="productive">赶工有度 · 疲劳 80 停工</option></select></label><p className="requirement">{w.organization.blocked}</p><button className="brass-button wide" onClick={()=>send({type:'AssignDelegate',enabled:!w.organization.delegation,proxy,budget})}>{w.organization.delegation?'停止后续轮次':'启动委托'}</button></>}</>;
 if(panel==='save')return <><div className="save-summary"><h2>{p.name}的旅程</h2><p>{dateText(w.tick)} · {w.works.length} 件作品</p><small role="status">{session.getSnapshot().saveStatus}</small></div><div className="button-grid"><button className="brass-button" onClick={()=>void session.save()}><Save size={16}/>保存此刻</button><button className="subtle-button" onClick={exportSave}><Download size={16}/>导出存档</button><button className="subtle-button" onClick={()=>input.current?.click()}><Upload size={16}/>导入存档</button><button className="subtle-button" onClick={()=>void session.recover().then(()=>notify('已恢复完整备份')).catch(e=>notify(e.message))}><RotateCcw size={16}/>恢复备份</button></div><input ref={input} type="file" accept=".json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void f.text().then(t=>session.import(t)).then(()=>{notify('已载入，时间保持暂停');onClose();}).catch(e=>notify(e.message));e.target.value='';}}/><p className="muted">桌面摆放、视角和未收取的成果也会保存。开发阶段不兼容旧版本存档，不兼容时请开启新旅程；个人手札单独导入导出。后台与离线时间不补算。</p><p className="muted">本机保留最近五份快照。清理浏览器或更换地址前，请导出备份。</p><button className="subtle-button" onClick={()=>void navigator.storage?.persist?.().then(v=>notify(v?'已获准持久存储':'浏览器未授予，请继续定期导出'))}>申请持久存储</button><div className="reset-row">{confirmReset?<><p>这会替换当前世界，先导出旧旅程。</p><button className="danger-button" onClick={()=>void session.reset().then(onClose).catch(e=>notify(e.message))}>确认重新开始</button><button className="subtle-button" onClick={()=>setConfirmReset(false)}>保留此生</button></>:<button className="text-button" onClick={()=>setConfirmReset(true)}>开启新旅程</button>}</div></>;
 if(panel==='journal')return <div className="full-journal">{w.log.slice().reverse().map(l=><article key={l.id} className={l.kind}><time>{dateText(l.tick)}</time><p>{l.text}</p></article>)}</div>;
 return <><p className="intro-quote">“旧琴在案，故人在侧。将一段相遇，慢慢放进自己的岁月。”</p><div className="help-steps"><p><b>一 · 桌面</b>左侧是手头的人与物，右侧「远近山河」是已知地点。拖动空白处移动桌面，滚轮缩放。右下角可归位、整理。</p><p><b>二 · 行事</b>点击行动方块，窗口中会出现槽位。卡牌可以拖入；也可点击槽位，再点击发亮的卡牌。双击卡牌会投入合适的空槽。</p><p><b>三 · 组合</b>先试试「交游」：放入陆青禾与沈知弦，可以小坐。合奏再加琴谱；把县志拿去谈，会是另一件事。同一张卡在不同方块里含义不同——旧琴可谋生，也可放进修养当蒲团；缺谱的创作会留下残稿。投入之前，都只是准备。</p><p><b>四 · 收获</b>点击开始后，人物与器物收进行动方块。完成时它会发亮；打开窗口，收取成果，卡牌回到桌面。</p><p><b>五 · 时光</b>空格暂停/继续。来信在桌面出现；重大来信会暂停时间。切到后台后需手动继续。</p><p><b>六 · 前路</b>两次合奏后，可用自己、旧琴与曲谱尝试「创作」。邀约要求实际演出。故人有自己的去处：沈先生可能赴下游，云岚会离开书院，小满也会求你。来信不要搁太久。</p></div><p className="muted"><BookOpen size={14}/> 点击卡牌可以查看属性。这些小小的线索，会告诉你它能进入哪些槽位。</p></>;
}
