import {knownVerbs} from '../domain/mortal-discovery';
import {useRef,useState} from 'react';
import {session} from '../application/game-session';
import {PLAYER,type World} from '../domain/model';
import {mortalDeck} from '../domain/mortal-cards';
import {collectionStock} from '../domain/notebook';
import {researchAvailable,setupKey} from '../domain/research';
import type {Collection,ResearchCommand,ResearchDomain,ResearchSetup} from '../domain/research-model';
import {researchDomains,researchItems,researchSteps} from '../content/research';
import './research.css';

export function newCollection(w:World,entries:Collection['entries'],setup?:ResearchSetup):Collection{return {id:crypto.randomUUID(),name:'未命名手札',notes:'',tags:[],pinned:false,order:Date.now(),version:1,entries,setup,journey:w.worldId,history:[]};}
const download=(text:string,name:string)=>{const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
export function ResearchPanel({w,notify}:{w:World;notify:(s:string)=>void}){
 const snap=session.getSnapshot(),r=w.research,book=snap.notebook;
 const [tab,setTab]=useState<'research'|'collections'|'notes'>('research'),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[editor,setEditor]=useState<Collection|null>(null),[selected,setSelected]=useState<string[]>([]),[located,setLocated]=useState<string[]>([]);
 const input=useRef<HTMLInputElement>(null);
 const setup:ResearchSetup=snap.researchDraft??{domain:'alchemy',inputs:[],step:'steady',intensity:'low'},d=researchDomains[setup.domain];
 const deck=mortalDeck(w),readonly=snap.pauses.includes('read_only');
 const update=(patch:Partial<ResearchSetup>)=>session.setResearchDraft({...setup,...patch});
 const send=(operation:ResearchCommand['operation'],item?:string)=>{const result=session.command({type:'Research',operation,domain:setup.domain,setup,item});if(!result.ok)notify(result.message);};
 const save=(c:Collection)=>{try{session.saveCollection(c);setEditor(null);notify('已保存个人收藏；未执行或消耗物品。');}catch(e){notify((e as Error).message);}};
 const entries=(ids:string[]):Collection['entries']=>ids.map(id=>({ref:'kind',id,name:deck.find(c=>c.id===id)?.name??researchItems[id]??id,quantity:1}));
 const status=(c:Collection)=>{if(!c.setup)return '整理清单／未指定操作';if(r?.evidence.some(e=>e.status==='explained'&&e.setup===setupKey(c.setup!)))return '本局已获完整讲解';const records=r?.records.filter(x=>setupKey(x.setup)===setupKey(c.setup!))??[];return records.length?`本局 ${records.length} 次观察 · ${records.some(x=>x.outcome==='injury')?'曾发生异常':'仍须结合条件判断'}`:c.setup.inputs.length===1&&c.setup.inputs[0].quantity===1&&c.setup.step==='steady'&&book.fixed.includes(c.setup.domain)?'通用固定方法 · 仍需实际条件':'本局待验证';};
 return <div className="research-panel"><nav className="research-tabs" aria-label="手札分类">{([['research','试验坊'],['notes','知识与笔记'],['collections','个人收藏']] as const).map(([id,name])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{name}</button>)}</nav>
 <fieldset disabled={readonly}>{snap.prepared.length>0&&<details className="prepared-collection" open><summary>收藏准备区 · 尚未执行</summary><p>{snap.prepared.map(id=>deck.find(c=>c.id===id)?.name??id).join('、')}</p>{!snap.researchDraft&&<div className="button-grid">{knownVerbs(w).map(verb=><button key={verb} onClick={()=>window.dispatchEvent(new CustomEvent('research-prepare',{detail:{verb,ids:snap.prepared}}))}>投入{{study:'研习',talk:'交游',create:'创作',work:'谋生',cultivate:'修养',travel:'行游'}[verb]}</button>)}</div>}<small>投入只准备适合槽位的卡牌，仍由你检查并开始行事。</small></details>}
 {tab==='research'&&<>{!r?<><h3>青溪试验坊</h3><p>公开工棚可供独行者采集、试作与请教散修。开始后占用此身；每次行动仍计入岁月和生活开销。</p><button className="brass-button" onClick={()=>send('enable')}>开启研究手札</button></>:<>
 <label className="field-label">研究领域<select value={setup.domain} onChange={e=>session.setResearchDraft({domain:e.target.value as ResearchDomain,inputs:[],step:'steady',intensity:'low'})}>{Object.entries(researchDomains).map(([id,x])=><option key={id} value={id}>{x.name}</option>)}</select></label>
 <p>{d.principle}</p><div className="button-grid"><button onClick={()=>send('gather')}>采集／抄录 · 90 分钟</button><button onClick={()=>send('rumor')}>打探 · 1 文／30 分钟</button><button onClick={()=>send('explain')}>请散修讲解 · 3 文／60 分钟</button><button onClick={()=>send('observe')} disabled={!researchAvailable(w,'xp.probe')}>用探灵器观察 · 30 分钟</button></div>
 <button disabled={!researchAvailable(w,'xp.link')} onClick={()=>send('introspect')}>协同内观 · 30 分钟（需运转心得）</button><h3>已知指引</h3>{r.evidence.filter(e=>e.domain===setup.domain&&(e.status==='explained'||e.status==='rumor')).map(e=><p key={e.id}>{e.status==='explained'?'完整讲解':'传闻'}：{e.text}</p>)}{!r.evidence.some(e=>e.domain===setup.domain)&&<p className="muted">尚无本局情报。可以凭公开原理独立试验。</p>}<h3>准备区</h3><p className="muted">选择卡牌与步骤仅作准备。单一主材可基础稳行；主材与辅料可自由试验，无需先有情报。</p>
 <div className="research-materials">{[d.base,...d.choices].map(id=><button key={id} aria-pressed={setup.inputs.some(x=>x.id===id)} onClick={()=>update({inputs:setup.inputs.some(x=>x.id===id)?setup.inputs.filter(x=>x.id!==id):[...setup.inputs,{id,quantity:1}]})}><b>{researchItems[id]}</b><small>可用 {researchAvailable(w,id)}</small></button>)}</div>
 <label className="field-label">操作步骤<select value={setup.step} onChange={e=>update({step:e.target.value as ResearchSetup['step']})}>{Object.entries(researchSteps).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className="field-label">强度<select value={setup.intensity} onChange={e=>update({intensity:e.target.value as ResearchSetup['intensity']})}><option value="low">小量／低强度 · 60 分钟</option><option value="high">全力／高强度 · 90 分钟</option></select></label>
 <p className="requirement">{setup.domain==='practice'?'抄本重复使用；高强度先花 15 分钟试运行，冲突时暂停并显示征兆。':'执行时消耗所选材料各一份；取消不退开工材料。逆炼须有调火炉。'}</p>
 <div className="button-row"><button className="brass-button" disabled={!!r.action} onClick={()=>send('experiment')}>执行试验</button><button disabled={!setup.inputs.length} onClick={()=>{setEditor(newCollection(w,setup.inputs.map(x=>({ref:'kind',id:x.id,name:researchItems[x.id],quantity:x.quantity})),setup));setTab('collections');}}>收藏当前组合</button></div>
 {r.warning&&<section className="research-warning" role="alert"><b>试运行出现气息逆行！继续会损失 8 点健康并产生不适。</b><p>可以停止、降强度试行，或请教。恢复方式：调息或温脉偏丹。</p><button onClick={()=>send('stop')}>立即收功</button><button onClick={()=>{session.setResearchDraft({...r.warning!,intensity:'low'});send('stop');}}>改为低强度准备</button><button onClick={()=>{const result=session.command({type:'Research',operation:'continue',domain:r.warning!.domain});if(!result.ok)notify(result.message);}}>承担后果继续</button></section>}
 {r.action&&<section className="research-running" aria-live="polite"><b>行事中 · {researchDomains[r.action.domain].name}</b><p>还需 {r.action.dueTick-w.tick} 分钟 · 此身已占用</p><button onClick={()=>session.waitForAction()}>等候研究进展</button><button onClick={()=>send('stop')}>中断研究</button></section>}
 {r.injury&&<p role="alert">逆行不适：暂不能继续试验。</p>}<button onClick={()=>send('recover')}>收功调息 · 120 分钟</button>
 <h3>可用成果</h3>{Object.keys(researchItems).filter(id=>!Object.values(researchDomains).some(x=>[x.base,...x.choices].includes(id))&&researchAvailable(w,id)>0).map(id=><div className="research-result" key={id}><b>{researchItems[id]} × {researchAvailable(w,id)}</b>{id==='xp.furnace'?<small>持有即可执行丹器逆炼步骤</small>:id==='xp.probe'?<small>持有即可使用材料观察入口</small>:id==='xp.strain'?<small>记录冲突现象，不提供修炼收益</small>:<button onClick={()=>send('apply',id)}>使用成果</button>}</div>)}
 <p className="muted">药膏／回元丹恢复健康，养神丹与蓄灵器降低疲劳；温脉偏丹解除逆行但增加疲劳；协同运转心得还能开启内观，观察功法衔接条件；消耗心得可用于调息与学识实践。</p>
 {r.records.at(-1)&&<p role="status">最近试验：{r.records.at(-1)!.text}</p>}
 </>}</>}
 {tab==='notes'&&<><h3>通用知识图鉴</h3>{Object.entries(researchDomains).map(([id,x])=><article key={id}><b>{x.name}</b><p>{x.principle}</p><small>{book.fixed.includes(id)?`已发现固定方法：${researchItems[x.base]}＋基础稳行 → ${researchItems[x.fixed]}`:'固定方法尚未发现，可独立小试。'}</small>{book.fixed.includes(id)&&<button onClick={()=>{session.setResearchDraft({domain:id as ResearchDomain,inputs:[{id:x.base,quantity:1}],step:'steady',intensity:'low'});setTab('research');}}>准备固定方法</button>}</article>)}<h3>本局研究笔记</h3><p className="muted">讲解揭示本局规则；一次成败仅为观察，不证明概率。</p>{r?.evidence.map(e=><article key={e.id}><b>{researchDomains[e.domain].name} · {{rumor:'传闻',explained:'已获讲解',observed:'试验观察',verified:'已验证'}[e.status]}</b><p>{e.text}</p><small>{e.source} · 本局 · 第 {Math.floor(e.tick/1440)+1} 日</small></article>)}<details><summary>历史旅程观察（不作为本局事实）</summary>{book.archive?.filter(x=>x.journey!==w.worldId).map(x=><article key={x.journey+x.id}><small>{x.journey}</small><p>{x.text}</p></article>)}</details><h3>尝试条件与结果</h3>{r?.records.map(x=><article key={x.id}><b>{x.setup.inputs.map(i=>researchItems[i.id]+' × '+i.quantity).join('、')}</b><small>{researchSteps[x.setup.step]} · {x.setup.intensity==='low'?'低强度':'高强度'} · {x.id}</small><p>{x.text}</p><button onClick={()=>{session.setResearchDraft(x.setup);setTab('research');}}>再次准备</button><button onClick={()=>{setEditor(newCollection(w,x.setup.inputs.map(i=>({ref:'kind',id:i.id,name:researchItems[i.id],quantity:i.quantity})),x.setup));setTab('collections');}}>收藏这次组合</button></article>)}</>}
 {tab==='collections'&&<><p>收藏是个人整理，名称和备注不会变成系统事实。种类引用用于备料；实例引用只指向该旅程的那一件。</p>
 <label className="field-label">搜索收藏<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="名称、备注、标签、物品"/></label><label className="field-label">适用性筛选<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部</option><option value="current">本局创建</option><option value="pending">本局待验证</option><option value="observed">本局有观察</option></select></label>
 <details><summary>从卡牌多选创建收藏</summary><div className="research-card-picker">{deck.map(c=><label key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>setSelected(selected.includes(c.id)?selected.filter(id=>id!==c.id):[...selected,c.id])}/>{c.name}</label>)}</div><button disabled={!selected.length} onClick={()=>setEditor(newCollection(w,entries(selected)))}>收藏所选卡牌</button></details>
 {editor&&<section className="collection-editor" aria-label="编辑收藏"><label className="field-label">收藏名称<input maxLength={80} value={editor.name} onChange={e=>setEditor({...editor,name:e.target.value})}/></label><label className="field-label">个人备注<textarea maxLength={2000} value={editor.notes} onChange={e=>setEditor({...editor,notes:e.target.value})}/></label><label className="field-label">标签（逗号分隔）<input value={editor.tags.join(',')} onChange={e=>setEditor({...editor,tags:e.target.value.split(/[,，]/).slice(0,20)})}/></label>{editor.entries.map((entry,i)=><div key={i} className="collection-entry"><span>{entry.name}</span><input aria-label={entry.name+'数量'} type="number" min={1} max={99} value={entry.quantity} onChange={e=>setEditor({...editor,entries:editor.entries.map((x,j)=>i===j?{...x,quantity:Number(e.target.value)}:x)})}/><select aria-label={entry.name+'引用方式'} value={entry.ref} onChange={e=>setEditor({...editor,entries:editor.entries.map((x,j)=>i===j?{...x,ref:e.target.value as 'kind'|'instance',journey:w.worldId,instanceId:w.mortal.assets[x.id]?.instanceId}:x)})}><option value="kind">种类引用</option><option value="instance">指定实例</option></select><button aria-label={'移除'+entry.name} onClick={()=>setEditor({...editor,entries:editor.entries.filter((_,j)=>i!==j)})}>移除</button></div>)}<label className="field-label">添加卡牌<select value="" onChange={e=>{if(e.target.value)setEditor({...editor,entries:[...editor.entries,...entries([e.target.value])]});}}><option value="">选择当前可见的卡牌</option>{deck.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field-label">手动排序<input type="number" min={0} value={editor.order} onChange={e=>setEditor({...editor,order:Number(e.target.value)})}/></label>{editor.setup&&<><label className="field-label">收藏步骤<select value={editor.setup.step} onChange={e=>setEditor({...editor,setup:{...editor.setup!,step:e.target.value as ResearchSetup['step']}})}>{Object.entries(researchSteps).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className="field-label">收藏强度<select value={editor.setup.intensity} onChange={e=>setEditor({...editor,setup:{...editor.setup!,intensity:e.target.value as ResearchSetup['intensity']}})}><option value="low">低强度</option><option value="high">高强度</option></select></label></>}<button onClick={()=>save({...editor,setup:editor.setup?{...editor.setup,inputs:editor.entries.map(x=>({id:x.id,quantity:x.quantity}))}:undefined})}>保存收藏</button><button onClick={()=>setEditor(null)}>取消编辑</button></section>}
 {book.collections.filter(c=>(c.name+c.notes+c.tags.join(' ')+c.entries.map(e=>e.name).join(' ')).toLowerCase().includes(search.toLowerCase())).filter(c=>filter==='all'||filter==='current'&&c.journey===w.worldId||filter==='pending'&&status(c).includes('待验证')||filter==='observed'&&status(c).includes('次观察')).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||a.order-b.order).map(c=><article key={c.id} className="collection"><h3>{c.pinned?'★ ':''}{c.name}</h3><small>组合版本 {c.version} · {status(c)}</small><p>{c.notes}</p><small>{c.tags.join(' · ')}</small>{collectionStock(w,c).map((row,i)=><div key={i}><span>{row.entry.name} × {row.entry.quantity} · {row.entry.ref==='instance'?'实例':'种类'}</span><small>库存 {row.total}／可用 {row.available}／缺少 {row.missing} · {row.status}</small></div>)}<div className="button-grid"><button onClick={()=>setEditor(structuredClone(c))}>编辑</button><button onClick={()=>save({...c,pinned:!c.pinned})}>{c.pinned?'取消置顶':'置顶'}</button><button onClick={()=>save({...c,order:Math.max(0,Math.min(...book.collections.map(x=>x.order))-1)})}>移至最前</button><button onClick={()=>{session.prepareCollection(c.id);setLocated(collectionStock(w,c).flatMap(x=>x.ids));notify('已准备当前可用部分；缺项保留，尚未执行。');if(c.setup)setTab('research');}}>准备已有材料</button><button onClick={()=>{const ids=collectionStock(w,c).flatMap(x=>x.ids);setLocated(ids);if(ids[0])window.dispatchEvent(new CustomEvent('research-locate',{detail:ids[0]}));}}>定位物品</button><button onClick={()=>session.deleteCollection(c.id)}>删除收藏</button></div>{c.setup&&<details><summary>关联试验记录</summary>{book.archive?.filter(x=>setupKey(x.setup)===setupKey(c.setup!)).map(x=><p key={x.journey+x.id}>{x.journey===w.worldId?'本局':'历史旅程（本局待验证）'} · {x.id} · {x.text}</p>)}</details>}{c.history.length>0&&<details><summary>此前组合版本 · {c.history.length}</summary>{c.history.map((h,i)=><small key={i}>版本 {h.version} · {h.journey} · 旧结论不证明当前组合</small>)}</details>}</article>)}
 {located.length>0&&<p role="status">已定位／准备：{located.map(id=>deck.find(c=>c.id===id)?.name??id).join('、')}</p>}
 <div className="button-row"><button onClick={()=>download(session.exportNotebook(),'山河问道-个人手札.json')}>导出个人手札</button><button onClick={()=>input.current?.click()}>导入个人手札</button></div><input ref={input} type="file" accept="application/json" hidden onChange={async e=>{const f=e.target.files?.[0];if(f)try{await session.importNotebook(await f.text());notify('手札已合并，同 ID 冲突保留副本。');}catch(err){notify((err as Error).message);}e.target.value='';}}/>
 </>}
 </fieldset></div>;
}
