import {describe,it,expect} from 'vitest';
import {createWorld,createLegacyWorld,assertWorld} from '../src/domain/world';
import {dispatch,advanceWorld} from '../src/domain/engine';
import {PLAYER,type World,type Command} from '../src/domain/model';
import {chains,methods,validateMortalContent} from '../src/content/mortal';
import {previewMortal,meetRole,releasePerson,tickMortal} from '../src/domain/mortal';
import {envelope,parseSave} from '../src/infrastructure/save';
import {checksum} from '../src/domain/random';
let seq=0;
function command(w:World,payload:Command){const r=dispatch(w,{actorId:PLAYER,expectedRevision:w.revision,commandId:'test.'+(++seq),payload});if(!r.result.ok)throw new Error(r.result.message);assertWorld(r.world);return r.world;}
function fresh(){return command(createWorld('mortal-test'),{type:'CreateMortal',name:'青禾',origin:'traveller',talent:'steady',acquaintance:false});}
function run(w:World,actionId:string,choice=''){w=command(w,{type:'MortalAction',actionId,choice});return advanceWorld(w,w.mortal.task!.dueTick);}
function travel(w:World,location:string){return w.entities[PLAYER].location===location?w:run(w,'travel.'+location);}
function rest(w:World){w=travel(w,'location.inn');if(w.mortal.paidUntil<w.tick+360)w=run(w,'rent');return run(w,'rest');}
function stage(w:World,id:string,choice?:string){const c=chains.find(c=>c.id===id)!;if(w.entities[PLAYER].fatigue>=60)w=rest(w);w=travel(w,c.location);return run(w,id,choice??c.stages[w.mortal.stages[id]??0].choices[0].id);}
function chain(w:World,id:string,first?:string){while((w.mortal.stages[id]??0)<chains.find(c=>c.id===id)!.stages.length)w=stage(w,id,(w.mortal.stages[id]??0)===0?first:undefined);return w;}
describe('凡尘篇内容与完整旅程',()=>{
 it('正式配置可校验，十条链均有可恢复选择',()=>{const c=validateMortalContent();expect(c.chains).toHaveLength(10);expect(c.shortSeeds).toHaveLength(24);expect(c.roles).toHaveLength(12);expect(c.places).toHaveLength(10);});
 it('默认独自成年开局，无免费修法、关系、药园或多套工具',()=>{const w=fresh();expect(Object.keys(w.entities)).toEqual([PLAYER]);expect(w.money).toBe(24);expect(w.mortal.foodDays).toBe(2);expect(w.mortal.people).toEqual({});expect(w.entities[PLAYER].knowledge).toEqual({});expect(w.organization.authorized).toBe(false);expect(w.entities[PLAYER].ageMinutes).toBeGreaterThan(18*365*1440);});
 it('创角只能执行一次，出身熟人有远方来历',()=>{let w=command(createWorld(),{type:'CreateMortal',name:'陆禾',origin:'artisan',talent:'focused',acquaintance:true});expect(Object.values(w.mortal.people)).toHaveLength(1);expect(Object.values(w.mortal.people)[0].worldStatus).toBe('travelling');const r=dispatch(w,{actorId:PLAYER,expectedRevision:w.revision,commandId:'again',payload:{type:'CreateMortal',name:'a',origin:'traveller',talent:'steady',acquaintance:false}});expect(r.result.ok).toBe(false);});
 for(const route of ['CH02','CH04','CH05','CH06'])it(route+' 能从独自开局，经非战斗自学完成初修应用',()=>{
  let w=chain(fresh(),'CH01');w=chain(w,route);expect(w.works).toHaveLength(1);w=chain(w,'CH09','independent');w=chain(w,'CH10');w=run(w,'method','MT01');w=travel(w,'location.inn');if(w.mortal.paidUntil<w.tick+1440)w=run(w,'rent');w=rest(w);
  w=run(w,'understand');w=run(w,'understand');w=run(w,'practice');expect(previewMortal(w,'practice').errors.join('')).toContain('纠错');w=run(w,'correct');w=run(w,'practice');if(w.entities[PLAYER].fatigue>50)w=rest(w);w=run(w,'practice');w=run(w,'apply');expect(w.mortal.completed).toBe(true);expect(w.entities[PLAYER].professions).toEqual({});expect(w.entities[PLAYER].longevityDays).toBe(0);expect(parseSave(envelope(w)).world).toEqual(w);
 });
 for(const channel of ['sect','mentor'])it(channel+' 可获得可靠来源且拒绝入宗不没收知识',()=>{let w=chain(fresh(),'CH01');w=stage(w,'CH09',channel);w=stage(w,'CH09');w=stage(w,'CH09','leave');expect(w.mortal.channel).toBe('independent');expect(w.mortal.stages.CH09).toBe(3);});
 for(const method of methods.slice(1))it(method.id+' 具备独立前置、纠错和等价公开应用场景',()=>{let w=fresh();w.mortal.stages.CH09=3;w.mortal.stages.CH10=2;w.mortal.skills.medicine=2;w.mortal.paidUntil=99999;w=run(w,'method',method.id);w=travel(w,method.location);for(const id of ['understand','understand','practice','correct','practice','practice','apply'])w=run(w,id);expect(w.mortal.applied).toBe(true);expect(w.entities[PLAYER].professions).toEqual({});});
 it('所有支线可以实际结清，不覆盖已完成作品',()=>{let w=fresh();w.money=500;w.mortal.foodDays=50;w.mortal.paidUntil=100000;for(const id of ['CH01','CH02','CH03','CH04','CH05','CH06','CH07','CH08','CH09','CH10'])w=chain(w,id);expect(w.works).toHaveLength(4);expect(w.mortal.flags).toContain('clue');expect(Object.values(w.mortal.contracts).every(c=>c.state==='completed')).toBe(true);});
 it('天赋降低对应实践成本，不跳过理解',()=>{let w=fresh();w.mortal.stages.CH09=3;w.mortal.stages.CH10=2;w.mortal.method='MT01';expect(previewMortal(w,'practice').minutes).toBe(90);expect(previewMortal(w,'practice').errors.join('')).toContain('理解');});
});
describe('生活、结算和时间一致性',()=>{
 it('开始只预留工钱，取消不赚钱；重复命令不结算两次',()=>{let w=fresh();const before=w.money,bank=w.mortal.bank;const e={actorId:PLAYER,expectedRevision:w.revision,commandId:'unique',payload:{type:'MortalAction',actionId:'work',choice:''} as Command};const r=dispatch(w,e);expect(r.result.ok).toBe(true);w=r.world;expect(w.money).toBe(before);expect(w.mortal.bank).toBe(bank-12);expect(dispatch(w,e).world).toBe(w);w=command(w,{type:'CancelMortal'});expect(w.money).toBe(before);expect(w.mortal.bank).toBe(bank);expect(w.mortal.task).toBeNull();});
 it('先付住宿再跨日不重复扣租；食物只结算一次',()=>{let w=fresh();w=travel(w,'location.inn');w=run(w,'rent');expect(w.money).toBe(20);w=advanceWorld(w,1440);expect(w.money).toBe(20);expect(w.mortal.foodDays).toBe(1);w=advanceWorld(w,1440);expect(w.mortal.foodDays).toBe(1);w=advanceWorld(w,4320);expect(w.money).toBe(18);});
 it('快进与小步推进在任务完成、跨日、旅期上保持一致',()=>{let w=fresh();w=command(w,{type:'MortalAction',actionId:'work',choice:''});const a=advanceWorld(w,4800);let b=w;for(let t=60;t<=4800;t+=60)b=advanceWorld(b,t);expect({...a,revision:0}).toEqual({...b,revision:0});});
 it('零钱、疲劳和受伤仍有恢复入口；有限帮工不能反复领取',()=>{let w=fresh();w.money=0;w.entities[PLAYER].fatigue=100;w.entities[PLAYER].health=40;w=run(w,'relief');expect(w.money).toBe(6);expect(w.mortal.foodDays).toBe(4);expect(previewMortal(w,'relief').errors.join('')).toContain('本周');w=rest(w);expect(w.entities[PLAYER].fatigue).toBe(45);expect(w.entities[PLAYER].health).toBe(50);});
 it('错误条件与资金不足不消耗材料、进度或随机人选',()=>{let w=fresh();const r=dispatch(w,{actorId:PLAYER,expectedRevision:w.revision,commandId:'wrong',payload:{type:'MortalAction',actionId:'CH02',choice:'ask'}});expect(r.result.ok).toBe(false);expect(r.world).toBe(w);expect(w.mortal.generation).toBe(0);});
 it('保存进行中的行动可恢复且只结算一次',()=>{let w=command(fresh(),{type:'MortalAction',actionId:'work',choice:''});w=parseSave(envelope(w)).world;w=advanceWorld(w,w.mortal.task!.dueTick);expect(w.money).toBe(36);const again=advanceWorld(parseSave(envelope(w)).world,w.tick);expect(again.money).toBe(36);expect(again.mortal.task).toBeNull();});
});
describe('身份生命周期与迁移',()=>{
 it('已绑定的相遇在人物死亡后不能继续现场行动',()=>{const w=fresh();const p=meetRole(w,'R03','same');p.worldStatus='dead';p.simulationTier='A';expect(()=>meetRole(w,'R03','same')).toThrow('已不在现场');});
 it('旧琴修复消耗真实材料，取消和交付均保留物主',()=>{let w=chain(fresh(),'CH01');w=stage(w,'CH04','preserve');const owner=w.mortal.assets['object.old-qin'].ownerId;expect(owner).not.toBe(PLAYER);w=command(w,{type:'MortalAction',actionId:'CH04',choice:'repair'});const id=w.mortal.task!.id;expect(w.mortal.assets['material.'+id].quantity).toBe(0);expect(w.mortal.assets['object.old-qin'].status).toBe('reserved');const paid=w.money;w=command(w,{type:'CancelMortal'});expect(w.money).toBe(paid);expect(w.mortal.assets['object.old-qin'].ownerId).toBe(owner);w=stage(w,'CH04','basic');w=stage(w,'CH04');expect(w.mortal.assets['object.old-qin'].status).toBe('returned');expect(w.mortal.assets['object.old-qin'].ownerId).toBe(owner);});
 it('来信会中断长段快进，不把人物拉回现场',()=>{let w=fresh();const p=meetRole(w,'R07','mail-source');p.contact='下游住处';releasePerson(w,p.id);w=command(w,{type:'MortalContact',personId:p.id,operation:'letter'});w=advanceWorld(w,8*1440);expect(w.tick).toBe(2*1440);expect(Object.values(w.mortal.messages)[0].state).toBe('delivered');});
 it('关系信任来自实际履约，答应和取消均不提前加分',()=>{let w=chain(fresh(),'CH01');w=travel(w,'location.pharmacy');w=command(w,{type:'MortalAction',actionId:'CH02',choice:'atlas'});const id=w.mortal.task!.personIds[0];expect(w.mortal.relationships[id]).toBeUndefined();w=command(w,{type:'CancelMortal'});expect(w.mortal.relationships[id]).toBeUndefined();w=run(w,'CH02','atlas');expect(w.mortal.relationships[id].trust).toBe(1);expect(w.mortal.relationships[id].facts[0]).toContain('完成约定');});
 it('一百个即时路人结束后不留下运行实例',()=>{const w=fresh();for(let i=0;i<100;i++){const p=meetRole(w,'R02','enc.'+i);releasePerson(w,p.id);}expect(Object.keys(w.mortal.people)).toHaveLength(0);expect(w.mortal.population.embodied).toBe(0);assertWorld(w);});
 it('同一相遇不重抽；关注后归档保护，远方来信不瞬移',()=>{let w=fresh();const p=meetRole(w,'R07','music');const id=p.id;p.contact='下游书社';releasePerson(w,id);expect(meetRole(w,'R07','music').id).toBe(id);releasePerson(w,id);w=command(w,{type:'MortalContact',personId:id,operation:'bookmark'});w=advanceWorld(w,7*1440);expect(w.mortal.people[id].worldStatus).toBe('travelling');w=command(w,{type:'MortalContact',personId:id,operation:'letter'});w=advanceWorld(w,9*1440);expect(w.mortal.people[id].worldStatus).toBe('travelling');expect(w.mortal.people[id].simulationTier).toBe('L1');expect(Object.values(w.mortal.messages)[0].state).toBe('delivered');});
 it('死者不能被岗位复用，旧身份不删除',()=>{const w=fresh();const p=meetRole(w,'R03','first');p.worldStatus='dead';p.simulationTier='A';const next=meetRole(w,'R03','second');expect(next.id).not.toBe(p.id);expect(w.mortal.people[p.id].worldStatus).toBe('dead');});
 it('欠款/作品等引用保护身份但不钉住现场',()=>{let w=chain(fresh(),'CH01');w=chain(w,'CH05');const p=w.mortal.people['character.teacher'];expect(p.pins.some(x=>x.pinReason==='作品来源')).toBe(true);expect(p.simulationTier).toBe('L1');w=advanceWorld(w,w.tick+31*1440);expect(w.mortal.people[p.id]).toBeTruthy();assertWorld(w);});
 it('旧档迁移保持物品、关系、权限和钱款，拒绝损坏原档',()=>{const w=createLegacyWorld();w.organization.authorized=true;const raw:any=envelope(w);delete raw.world.mortal;raw.world.rulesVersion='1.0.0';raw.world.contentVersion='0.1.0';raw.saveSchemaVersion=1;raw.rulesVersion='1.0.0';raw.contentVersion='0.1.0';raw.contentHash='73eec9433990df2aef85c33ee606024d8940ae7e04aeb7acc1344594b98ced48';const canonical=JSON.stringify(raw.world,(_k,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.keys(v).sort().map(k=>[k,v[k]])):v);raw.payloadChecksum=checksum(canonical);const original=JSON.stringify(raw);const migrated=parseSave(raw);expect(migrated.world.mortal.mode).toBe('legacy');expect(migrated.world.entities).toEqual(w.entities);expect(migrated.world.relations).toEqual(w.relations);expect(migrated.world.organization.authorized).toBe(true);expect(JSON.stringify(raw)).toBe(original);raw.world.money++;expect(()=>parseSave(raw)).toThrow('校验');});
});
